# Generated by Django 3.2.9 on 2021-12-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=25)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=300)),
                ('added_At', models.DateField()),
                ('image', models.ImageField(upload_to='kidswear/images')),
            ],
        ),
    ]
