# Generated by Django 3.2.9 on 2021-12-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidswear', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
