# Generated by Django 4.0 on 2021-12-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidswear', '0005_order_delete_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='username',
        ),
    ]
