# Generated by Django 4.0 on 2021-12-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidswear', '0008_alter_order_placed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_At',
            field=models.DateField(default=''),
        ),
    ]
