# Generated by Django 4.0 on 2021-12-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidswear', '0011_remove_order_placed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_At',
            field=models.DateField(default=(2021, 12, 21)),
        ),
    ]
