# Generated by Django 4.0 on 2021-12-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidswear', '0012_order_placed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='placed_At',
        ),
    ]
