# Generated by Django 4.0 on 2021-12-12 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kidswear', '0015_remove_order_placed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_At',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
