# Generated by Django 4.0 on 2021-12-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidswear', '0020_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
