# Generated by Django 4.0 on 2021-12-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidswear', '0022_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_At',
            field=models.DateField(),
        ),
    ]
