# Generated by Django 4.0 on 2021-12-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidswear', '0025_alter_order_placed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_At',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
