# Generated by Django 4.0 on 2021-12-12 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidswear', '0026_alter_order_placed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_At',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
